### ISSUE TITLE
Version code extensions

### ISSUE THREAD

**Issue by gladed** [gladed/gradle-android-git-version#27]
For projects with multiple APKs it might be nice to slot in other values (API-level, Platform, Screen size, etc.). Right now this is kind of tricky to do.

**Comment by HPGlade** [comment]
As mentioned in #31 there could be a user-customizable list of digits to fill in with different content.

Considerations:

* Don't exceed 2100000000. (https://developer.android.com/studio/publish/versioning.html#appversioning)
* Consider API Level (e.g. 25=N) and Screen Size (e.g. 34=xlarge) as components of the version code (https://developer.android.com/google/play/publishing/multiple-apks.html#VersionCodes):

So here's a provisional list of inclusions:
* SS (screen size)
* AA (API Level)
* M (major version number 1.x.x)
* N (minor version number x.2.x)
* P (patch version number x.x.3)
* BBBB (build number, e.g. 2838 for number of commits since beginning)
* UUU (update number, e.g. 102 for number of updates since last tag)

Others?

**Comment by gladed** [comment]
As mentioned in #31 there could be a user-customizable list of digits to fill in with different content.

Considerations:

* Don't exceed 2100000000. (https://developer.android.com/studio/publish/versioning.html#appversioning)
* Consider API Level (e.g. 25=N) and Screen Size (e.g. 34=xlarge) as components of the version code (https://developer.android.com/google/play/publishing/multiple-apks.html#VersionCodes):

So here's a provisional list of inclusions:
* SS (screen size)
* AA (API Level)
* M (major version number 1.x.x)
* N (minor version number x.2.x)
* P (patch version number x.x.3)
* BBBB (build number, e.g. 2838 for number of commits since beginning)
* UUU (update number, e.g. 102 for number of updates since last tag)

Others?

**Comment by gladed** [comment]
As discussed in #31, we would call this `codeFormat`. 

`parts` and `multiplier` would be deprecated with this change. They should continue to function as-is where `codeFormat` is not supplied for backwards compatibility.

**Comment by gladed** [comment]
(mostly) fixed in 0.3.0 / 52356447

**Comment by gladed** [comment]
(Didn't do BBBB, SS, or AA. Maybe later.)

**Comment by gladed** [comment]
Let me know what you think @artky -- hopefully this will address your use case well!
