### ISSUE TITLE
Plugin causes pre-commit hook to fail

### ISSUE THREAD

**Issue by bnvinay92** [gladed/gradle-android-git-version#36]
When I try to run this task in a pre-commit hook, I get an error:
`Bare Repository has neither a working tree, nor an index`
with gradle failing on `androidGitVersion.code()`.

**Comment by gladed** [comment]
Is your pre-commit hook operating on a shallow clone somehow? This plugin needs access to the full commit history so it can find the most recent tags.

(I could disable the error in this case, but of course would result in "unknown" for version names and 0 for codes.)

**Comment by bnvinay92** [comment]
There are no tags yet. It works fine as a pre-push hook. It isn't a shallow clone.

**Comment by HPGlade** [comment]
For some reason, `GIT_WORK_TREE` isn't set during execution of a pre-commit hook. So you could try something like this:

    GIT_WORK_TREE=".." ./gradlew androidGitVersion

Let me know how it goes!

**Comment by gladed** [comment]
For some reason, `GIT_WORK_TREE` isn't set during execution of a pre-commit hook. So you could try something like this:

    GIT_WORK_TREE=".." ./gradlew androidGitVersion

Let me know how it goes!

**Comment by bnvinay92** [comment]
That works. Could there be any unintended side effects from this?

**Comment by gladed** [comment]
I don't think so because:

* `.git/hooks/pre-commit` only affects behavior on the machine where it is installed (presumably yours)
* The line above doesn't actually set `GIT_WORK_TREE` except in the gradle process 

If you had other plugins messing around with git then perhaps they would be affected. Beyond that it seems safe.

I'll close this issue now, but feel free to comment if you run into anything else related to it, and thanks for letting me know!
