### ISSUE TITLE
androidGitVersion.code() without tag

### ISSUE THREAD

**Issue by yshinkarev** [gladed/gradle-android-git-version#38]
I can set for androidGitVersion.name() next format:
`format = '%branch%'`
So, if I have branch 1.3.2, then I get versionName "1.3.2". OK.
androidGitVersion.code() return always 0, because I do set tag value.
But I think it's normal use case:
git branch = 1.3.2
androidGitVersion.name() = "1.3.2'
androidGitVersion.code() = 103020

**Comment by gladed** [comment]
Tags are better for versioning since they don't move around like branches can.

But to support this use case we would need a flag to completely disable looking at tags, e.g. `useTags=false`, and try to extract the version from the current branch. In that mode, building from a branch like `master` or `develop` would never result in a working version name. Seems like a pretty specialized case.

Is there some reason you can't use tags? For example in this case you could assign a tag 1.3.2 anywhere in the branch to produce the result you're looking for.

**Comment by gladed** [comment]
Haven't heard back so closing this request.
