### ISSUE TITLE
Question: Using git version for subprojects

### ISSUE THREAD

**Issue by AllanWang** [gladed/gradle-android-git-version#39]
What is the best way to add git versioning if I have multiple subprojects?

Say I have a library module and a sample module and they both should have the same version code and name. Currently I'm adding the plugin and settings to both `app/build.gradle` and `library/build.gradle` but I'm wondering if it could be done in the root gradle through sub projects.

**Comment by gladed** [comment]
Unfortunately, at present, I don't see a lot of help for this use case in https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl.

I typically version libraries and apps differently using `prefix` and `onlyIn` so that a library I'm distributing doesn't move versions when the app changes. So in the case I would have different `androidGitVersion` blocks anyway. And if you're not distributing the library itself, then it's somewhat likely that its version code is not very important -- it's the versionCode/versionName of the app that will be seen by users.

But if you come up with anything that works better for your use case, let me know!
