### ISSUE TITLE
Release candidate in versionName, versionCode

### ISSUE THREAD

**Issue by sergioboi** [gladed/gradle-android-git-version#47]
In my flow i have rc in versionName and versionCode for testers. Can i with your plugin read some data from git tag and interpreted it like rc number? Or i can write some code for support that feature. What you think about it?

**Comment by gladed** [comment]
This should be possible, can you provide some example tags and the versionName/versionCode output you would want to see?

**Comment by sergioboi** [comment]
tag = 0.9.9-rc1,  versionName=0.9.9-rc1,  versionCode=0900901 for example

**Comment by gladed** [comment]
We don't have a good way for handling hypenated identifiers at this time, since there's no clean way to translate them to a digit. What digit(s) would be used for the following?

`0.9.9-alpha`
`0.9.9-alpha.beta`
`0.9.9-alpha2`
`0.9.9-beta.2.5`
`0.9.9-rc1`

Currently this plugin doesn't hard-code semantic versioning, it just looks for digits. So `0.9-rc1` would actually show up as version code 9001 and `0.9-alpha2` would look like version code 9002.

Another approach I have used is to go ahead and rev the patch number for each pre-release, e.g. `0.9.9-alpha1`, `0.9.10-alpha2` etc.

**Comment by sergioboi** [comment]
What u think about support rc in tag format? I can try to write code for support that feature

**Comment by GladeDiviney** [comment]
If you want to do this in your own build file code you can easily inspect `name()` and modify `version()`. But at this time I don't see a good generalized approach.
