### ISSUE TITLE
versionname started to include very long sha hash

### ISSUE THREAD

**Issue by eikaramba** [gladed/gradle-android-git-version#52]
something is strange and i cannot explain it, because we didn't changed the way how we use your plugin. I think i updated your plugin to latest 4.4 recently, so it could be because of that.
see the following screenshot
![grafik](https://user-images.githubusercontent.com/1320525/43614888-77cad46c-96b5-11e8-82da-69c939ada58a.png)

here u see that normally we used to have a nice short sha hash, but recently we start to get the full sha hash too after the short one.

this is the gradle code
```
    androidGitVersion {
        codeFormat = 'AMMNNPPBB'
        variants applicationVariants
        hideBranches = ['master']
    }

.......and later
        versionName androidGitVersion.name()
        versionCode androidGitVersion.code()
```
the build was compiled from master.

if i look at the default for `format "%tag%%-count%%-commit%%-branch%%-dirty%"` i don't see why this is happening, as there is only commit, branch(is not there because hidden, sry you don't see this in the screenshot) and dirty(exists at the very end in this example)

for me it seems he is displaying the full sha hash as for the branch name....

**Comment by eikaramba** [comment]
also i think your readme has an error because the default format seems to misspell where the percentage symbol is placed, see above where i just copied it from your readme.

**Comment by gladed** [comment]
Was this performed on a commit from a detached head? It looks like git is giving the full sha1 instead of a branch name because there is no branch.

The string looks a bit strange because the `-` character is inside the delimiters. This is actually intentional so that the each part (including the `-` character) disappears when not needed.

**Comment by eikaramba** [comment]
i don't think so, but actually there is something interesting if i look at the commit from which it was build:
![grafik](https://user-images.githubusercontent.com/1320525/43615837-df504cd0-96b9-11e8-88ae-6df75062002e.png)

I guess you are right, i can test tomorrow if the format looks fine if it was builded from a regular commit. in this case it was build from a remote merge.

regarding the default format string, got it. understand it now.

**Comment by gladed** [comment]
Let me know -- many CI systems optimize or otherwise manipulate their local git repo so that it doesn't look like what you might get on your local system and this is a common source of problems for any git-based auto-versioning code. You'll need an "unshallow" fetch on a normal branch for all of this to work.

**Comment by eikaramba** [comment]
ok a regular build went through bamboo and yes, it was actually because of the remote merge it seems. maybe that is something which can be added to the readme, but at least we now know why it happens.
