### ISSUE TITLE
Recent update of jgit breaks compatibility with older Gradle versions

### ISSUE THREAD

**Issue by kruton** [gladed/gradle-android-git-version#82]
It looks like the jgit dependency was bumped in a recent patch revision, but this breaks compatibility with Gradle 4.6 and perhaps newer versions. Gradle [switched jgit versions](https://github.com/gradle/gradle/commit/4f48f4d18ff497aafd4b6f0ff516620a08fd4ceb) starting with Gradle 5.0.0. The new call to [`DescribeCommand#setTags()`](https://github.com/eclipse/jgit/blob/f40b39345cd9b54473ee871bff401fe3d394ffe3/org.eclipse.jgit/src/org/eclipse/jgit/api/DescribeCommand.java#L190) doesn't work in jgit versions before 5.0.

According to the [Android build tools page](https://developer.android.com/studio/releases/gradle-plugin#updating-gradle), you need to have build-tools version 3.4.0 or higher before you can move to Gradle 5+.

**Comment by gladed** [comment]
Since this plugin has its own dependency on `jgit` I'm confused why gradle's own internal version dependency would prevent this plugin from working.

In any case, it's a good warning to log here and thanks for raising the issue.

**Comment by gitkobold** [comment]
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: com.gradle.scan.plugin.BuildScanException: The build scan plugin is not compatible with Gradle 6.0 and later.
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Please use the Gradle Enterprise plugin instead.
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] at com.gradle.scan.plugin.BuildScanPlugin.a(SourceFile:99)
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] at com.gradle.scan.plugin.BuildScanPlugin.apply(SourceFile:37)
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:51)
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:181)
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] at org.gradle.api.internal.plugins.DefaultPluginManager.access$300(DefaultPluginManager.java:51)
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:276)
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:159)
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:156)
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:49)
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:156)
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] ... 140 more
